version: "3"

# defining services (i.e. containers)
services:
  mysql:
    build: # path to the dockerfile from which the image gets build
      context: .
      dockerfile: ./db/dockerfile.mysql # relative to context
    volumes:
      - ./db:/docker-entrypoint-initdb.d  # relative to docker-compose.yml
    image: original_mysql_world # the name of the image
    container_name: mysql-container
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - local-net

  linux:
    build:
      context: .
      dockerfile: ./app/dockerfile.app
    volumes:
     - ./app:/app
    image: api-app
    container_name: api-app-container
    networks:
     - local-net
    depends_on:
     - mysql
    tty: true

# defineing the networks 
networks:
  local-net:
    driver: bridge
