# specifying the Docker image 
FROM mysql

# exposing port 
EXPOSE 3306

# copying MySQL config file to linux 
ADD ./db/my.cnf /etc/mysql/conf.d/my.cnf # relative to context specified in docker-compose.yml

#docker runに実行される
CMD ["mysqld"]
